### PR TITLE
add ERD to docs folder. Fix linters

### PR DESCRIPTION
**Pull request by realisticattorney**
Milestone 1: ERD

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
Hello team, you have done a great job. :muscle: 
For this milestone to be approved, Kindly fix the below issue :point_down: 
- [ ] You have two unnamed entities. They should be named `user` and `post`.

Kindly fix this before submitting another review. 

_Feel free to reach out to me on slack `@oloomoses`_

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required
Hi!!
Good job with your ERD, but there are two small changes that you have to do before moving to the next milestone:

- [ ]  [REQUIRED] Please separate these links to make your ERD easy to understand and to make it clearer:


- [ ] [REQUIRED] Pull request must have a description.

I am sure that it will be super quick to implement!
Kindly fix the pointed out issue before requesting the next code review.
Happy coding
Rindra Josia :+1:

**Comment by realisticattorney** [comment]
It's perfectly clear and easy to understand. This review is not helpful. I cant waste an hour waiting for a review to tell me this. I have a project to do.

The red circle on the left is confusing only if you dont know that a foreign key cant be foreign within its own entity, thus, it should be going to the User entity. And if someone doesn't know that maybe they shouldn't be looking an ERD
The rest of the circles has a small curve just before the union that tells the direction. Again, this is clear. I've build stuff with far worse instructions manuals than this, and those were made by engineers.

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @realisticattorney, I understand the excitement to finish with the "boring" stuff and get to the coding part at once, most times they save us a lot of time in the long run.

Just this one change 🙏 and you will be on your way into the actual coding 💪 

- [ ] On each of the tables' primary key field, there is no need to attach the table's name as a prefix to IDs, it makes more sense to do that when they are been referenced as Foreign Key, eg, under the User table, PK should just be ID instead of user_id, under Post table, PK should just be ID instead of post_id, repeat same for Comment, Friendship and Like table. I hope you find this useful even in future implementations.

I am sorry this part was omitted by my colleagues.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**
Hello @realisticattorney
Great work implementing the required changes.👏👏👏
You can merge the branches and keep on working.

Happy coding💻💻

**Pull request merged**
